### ISSUE TITLE
Move from vorburger/MariaDB4j to MariaDB4j org, or even MariaDB?

### ISSUE THREAD

**Issue by vorburger** [MariaDB4j/MariaDB4j#238]
In #213, @srbala has raised this:

> @vorburger would you consider moving this project to it's own organisation? Name MariaDB4jseems available https://github.com/mariadb4j

I'm open to this if it can help get more participation (notably people helping out with answering open issues, raising pull requests, and cross code reviewers from others).

**Comment by vorburger** [comment]
Before I do, this idea reminds me of something I had actually been meaning to do for ... years - perhaps the Good People of https://github.com/MariaDB, specifically the maintainers at https://github.com/MariaDB/mariadb-connector-j, would be open to welcoming this project? Let's just ask! See https://jira.mariadb.org/browse/CONJ-694 ...

**Comment by vorburger** [comment]
@srbala I have just reserved https://github.com/MariaDB4j, just in case [CONJ-694](https://jira.mariadb.org/browse/CONJ-694) doesn't work out.

**Comment by srbala** [comment]
Sounds good. Looking forward to participate in anyway i can.

**Comment by vorburger** [comment]
https://jira.mariadb.org/browse/CONJ-694 is moving...

**Comment by vorburger** [comment]
Re-opening this old issue, motivated by https://opencollective.com/MariaDB4j approval from Open Source Collective requiring moving away from http://github.com/vorburger.

So I have moved https://github.com/vorburger/MariaDB4j to https://github.com/MariaDB4j/MariaDB4j (finally).

PS: I'll may or may not explore moving again under https://github.com/MariaDB as per old https://jira.mariadb.org/browse/MDBF-219 - I first need to be sure that I'll still have permissions there... 😄  I'll explore that (with a testing repository) when I have a bit more time for that than I have right now.
