### ISSUE TITLE
A problem with windows security update - KB4586793

### ISSUE THREAD

**Issue by itamarlev** [MariaDB4j/MariaDB4j#408]
after installing this latest win10 security update the unit tests are throwing the following:
Caused by: ch.vorburger.exec.ManagedProcessException: Program [C:\Users\XXX\AppData\Local\Temp\MariaDB4j\base\bin\mysql.exe, --port=3306] (in working directory C:\Users\XXX\AppData\Local\Temp\MariaDB4j\base) failed, exitValue=1, last 100 lines of console:
ERROR 2019 (00000): Can't initialize character set unknown (path: compiled_in) 

After uninstalling the update there's another security update KB4570333.
When removing that one, the issue is resolved.
 
please advise what could be done here. These security updates are mandatory here..

**Comment by vorburger** [comment]
Somehow the character set is unknown for you. No idea what could cause this. Let's close this issue, and reopen it if someone wants to contribute a fix for this corner case.

**Comment by vorburger** [comment]
@itamarlev #52 sounds like a good approach for fixing this; perhaps you would like to contribute a PR for that FR to solve this issue.

**Comment by itamarlev** [comment]
tried 
        db.getConfiguration().getArgs().add("--character-set-server=utf8");
        db.getConfiguration().getArgs().add("--collation-server=utf8_general_ci");
but it's not working, 
I guess the code doesn't support it yet..

**Comment by vorburger** [comment]
@itamarlev perhaps if in addition to specifying the character set for the DB server (as above) you also (or instead?) specify the character set of the JDBC client [as shown here](https://github.com/vorburger/MariaDB4j/issues/90#issuecomment-337182854) with something like `?characterEncoding=utf-8&useUnicode=true` in the JDBC connection URL you have more luck?

**Comment by itamarlev** [comment]
added to the url
jdbc:mysql://%s:%s/?characterEncoding=utf-8&useUnicode=true
unfortunately no success here either

**Comment by itamarlev** [comment]
I suspect that the problem is in the ch.vorburger.mariadb4j.DB class line 195
InputStream from = IOUtils.toInputStream(command, Charset.defaultCharset());
getting the default charset cannot be changed.
The solution from my end was to go to Windows-> control panel -> region 
into the administrative tab --> change locale and checking the "Beta: Use Unicode UTF-8 for worldwide support"
that solve the issue.

**Comment by vorburger** [comment]
Interesting. If you think it could help to be able to specify the Charset
to use there via a parameter, I would be happy to merge a PR from you with
that.

**Comment by vorburger** [comment]
Closing ancient issue which hasn't seen any community engagement in 2 years; any future readers, please open a new issue, or (better) a PR with a fix!
