### ISSUE TITLE
It should be possible to automatically cleanup the data dir but keep the base dir

### ISSUE THREAD

**Issue by Bios-Marcel** [MariaDB4j/MariaDB4j#481]
Currently there's `setDeletingTemporaryBaseAndDataDirsOnShutdown`, but I think it'd be handy to be able to set these separately. For backwards compatibility reasons the existing method should be kept though. It could just delegate to the other two.

I could try making a PR for this if you'd like.

**Comment by vorburger** [comment]
> I could try making a PR for this if you'd like.

sure, PRs are always welcome!

**Comment by vorburger** [comment]
I'm wondering if what you actually really want here may simply be #416?

**Comment by vorburger** [comment]
Closing ancient issue which hasn't seen any community engagement in 2 years; any future readers, please open a new issue, or (better) a PR with a fix!
