### ISSUE TITLE
mariaDB4j-springboot fails to start on 2.6.0 (2.5.3 works)

### ISSUE THREAD

**Issue by jejanim** [MariaDB4j/MariaDB4j#632]
While working on an implementation for a simulator project I noticed that the "new" version 2.6.0 of artifact mariaDB4j-springboot throws errors upon starting. Downgrading to the previous release 2.5.3 "fixes" it, so one could assume that something broke or changed there. 
I think it could be related to the tmpDir change https://github.com/vorburger/MariaDB4j/commit/a0d2a66ed853e4622b05f065e62fe9c852081ff3, but that's just a guess \_o.o_/

_(separated error message to improve readability, originally there were no line breaks)_

```
ch.vorburger.exec.ManagedProcessException: 
  Program [C:\Users\USERNAME\AppData\Local\Temp\MariaDB4j\base\bin\mysql_install_db.exe, 
      --datadir=C:\Users\USERNAME\AppData\Local\Temp\MariaDB4j\data\3306, 
      --tmpdir=C:\Users\USERNAME\AppData\Local\Temp\MariaDB4j\tmp\3306
  ] (in working directory C:\Users\USERNAME\AppData\Local\Temp\MariaDB4j\base) 
  failed, 
  exitValue=7, 
  last 100 lines of console:

C:\Users\USERNAME\AppData\Local\Temp\MariaDB4j\base\bin\mysql_install_db.exe: 
  unknown variable 'tmpdir=C:\Users\USERNAME\AppData\Local\Temp\MariaDB4j\tmp\3306'
```

Configuration is at a bare minimum:

```java
@Configuration
public class DatabaseConfiguration {
    public MariaDB4jSpringService mariaDb() {
            MariaDB4jSpringService mariaDb = new MariaDB4jSpringService();
            mariaDb.setDefaultPort(3306);
            return mariaDb;
    }
```

**Comment by vorburger** [comment]
@jejanim I suspect that this could be some Windows specific issue.

The [`MariaDB4JSpringConfigurationTest`](https://github.com/vorburger/MariaDB4j/blob/main/mariaDB4j-springboot/src/test/java/ch/vorburger/mariadb4j/springboot/autoconfigure/MariaDB4JSpringConfigurationTest.java) has test coverage for this.

That test works for me, on Linux. Does it fail when you run it on Windows:

**Comment by jejanim** [comment]
Yes it does and the stack trace implies it fails with the exact same error.

```
java.lang.AssertionError: 
Expecting:
 <Unstarted application context org.springframework.boot.test.context.assertj.AssertableApplicationContext[startupFailure=org.springframework.beans.factory.BeanCreationException]>
to have a single bean of type:
 <ch.vorburger.mariadb4j.springframework.MariaDB4jSpringService>:
but context failed to start:
Caused by: ch.vorburger.exec.ManagedProcessException: 
  Program [C:\Users\USERNAME\AppData\Local\Temp\MariaDB4j\base\bin\mysql_install_db.exe, 
    --datadir=C:\Users\USERNAME\AppData\Local\Temp\MariaDB4j\data\64673, 
    --tmpdir=C:\Users\USERNAME\AppData\Local\Temp\MariaDB4j\tmp\64673] 
  (in working directory C:\Users\USERNAME\AppData\Local\Temp\MariaDB4j\base) failed, 
exitValue=7, 
last 100 lines of console:
 C:\Users\USERNAME\AppData\Local\Temp\MariaDB4j\base\bin\mysql_install_db.exe: 
  unknown variable 'tmpdir=C:\Users\USERNAME\AppData\Local\Temp\MariaDB4j\tmp\64673'
```

**Comment by jejanim** [comment]
Sure.
It will, however, take quite some time. I'm not too familiar with actions because I am a gitlab person. 😛

**Comment by vorburger** [comment]
@jejanim and perhaps @chrisbloe or anyone else reading along here:

Now that we can clearly see the error reported above in the buil log of PR #638, we can try to fix it... but I'm not yet immediately understanding what to make of `unknown variable 'tmpdir=...'` - do any of you? Would you be willing to try out something:

If you "manually" (from a `cmd.exe` Terminal, or whatever the "shell" is in Windows nowadays) launch:

    C:\Users\USERNAME\AppData\Local\Temp\MariaDB4j\base\bin\mysql_install_db.exe --datadir=C:\Users\USERNAME\AppData\Local\Temp\MariaDB4j\data\64673 --tmpdir=C:\Users\USERNAME\AppData\Local\Temp\MariaDB4j\tmp\64673

does that work, or give you the same error? I don't suppose that for some reason `mysql_install_db.exe` doesn't have a `--tmpdir` argument, only on Windows? Or does that `unknown variable 'tmpdir=...` mean something else? Anyone interested in reading up on https://www.google.com/search?q=mysql+unknown+variable what could be causing this (only on Windows), and sharing it here?

**Comment by chrisbloe** [comment]
Looking at https://mariadb.com/kb/en/mysql_install_dbexe, `datadir` is listed as an option, but `tmpdir` isn't...

I'll keep looking...

**Comment by tomwhoiscontrary** [comment]
Same version builds cleanly for me on Fedora Linux 36, after installing MariaDB. On that machine i have MariaDB 10.5.18-MariaDB. Maybe the version on Ubuntu is just too old?

**Comment by vorburger** [comment]
With the merge of #638, Windows is now tested on CI and the problems shown above should be resolved.

I am therefore closing this old issue (which mixed a number of problems anyway) at this stage.

Please open new issues for any new problems - if they are still occuring with the 3.0.1 or later release.
