### ISSUE TITLE
Fix Sonatype Lift Findings

### ISSUE THREAD

**Issue by vorburger** [MariaDB4j/MariaDB4j#686]
Is anyone reading along motivated to contribute PRs fixing [these Sonatype Lift findings](https://lift.sonatype.com/results/github.com/vorburger/MariaDB4j/01GTPTGBMN0CHXAVW6KKG7CA9Z/?tab=results)?

**Comment by vorburger** [comment]
@mosesn given your work on https://github.com/vorburger/ch.vorburger.exec/pull/103, could this possibly interest you? Up to you!

**Comment by TheKnowles** [comment]
Lift got decommissioned. Were the results cached anywhere for review?

**Comment by vorburger** [comment]
> Lift got decommissioned. Were the results cached anywhere for review?

Oh, wow, yeah; see https://community.sonatype.com/t/sunset-notice-sonatype-lift/10940

> Were the results cached anywhere for review?

Nope, I hadn't copied them anywhere, unfortunately.

Let me close this issue, as this is (now) "unactionable".

If you @TheKnowles (or anyone else reading along here) are interested in making "code quality" contribution, perhaps #736 could interest you?
