### ISSUE TITLE
Support for sequences

### ISSUE THREAD

**Issue by Lonzak** [MariaDB4j/MariaDB4j#727]
I tried mariadb4j and it worked nicely until it stumbled over `sequences`.
MariaDB supports sequences starting from [Version 10.3.](https://mariadb.com/kb/en/sequence-overview/)
So the current version of mariaDB which MariaDB4j is using must be below 10.3? Can I see that version somewhere?

> MariaDB4j supports using existing native MariaDB binaries on the host system rather than unpacking MariaDB from the classpath. This is useful if you need a newer version than is currently distributed [...]

So if I would supply a newer version of mariaDB also sequences would be supported?

Thanks!

**Comment by vorburger** [comment]
> So the current version of mariaDB which MariaDB4j is using must be below 10.3? Can I see that version somewhere?

see https://github.com/vorburger/MariaDB4j/blob/main/mariaDB4j/pom.xml

> So if I would supply a newer version of mariaDB also sequences would be supported?

@Lonzak Yeah, that's correct. If you would be interested in raising a PR to contribute to this project for this, you could pick up #710, which made a great start with upgrading the native binaries.

**Comment by vorburger** [comment]
@Lonzak in #771 @TheKnowles has contributed (and it got merged as part of #772)  a newer version MariaDB binaries.

I suspect that that will fix this issue. Would you like to (for now, either use https://jitpack.io/#vorburger/MariaDB4j/main-SNAPSHOT or locally build and) try it out?

**Comment by Lonzak** [comment]
Sounds promising! Unfortunately I currently I do not have the time to try it out...Maybe someone else in the community can?

**Comment by vorburger** [comment]
@Lonzak I suspect those newer version MariaDB will support SQL for sequences.

Let's close this issue; any future readers, please open a new issue, or (better) a PR with a fix if any is required!
