### ISSUE TITLE
Release 3.0.2

### ISSUE THREAD

**Issue by fmartinou** [MariaDB4j/MariaDB4j#902]
Hello,

Thank you for your work.

[On Maven Central](https://central.sonatype.com/artifact/ch.vorburger.mariaDB4j/mariaDB4j), I'm unable to find the latest release `3.0.2`.
The latest available is the `3.0.1`; am I missing something?

![image](https://github.com/MariaDB4j/MariaDB4j/assets/16061231/dba733da-5a3d-4234-8f0d-f50c8581bff4)

**Comment by vorburger** [comment]
Hm, that's weird... did I "forget" (?) to publish 3.0.2 to central?

Clearly I intended to, given https://github.com/MariaDB4j/MariaDB4j/releases/tag/mariaDB4j-3.0.2 ...

I usually have a release bug, but #696 doesn't mention 3.0.2 - and was in May, whereas the tag is apparently from Sep.

I'll see if I can do a release one of these days...

**If you use MariaDB4j professionally, please consider to, either:**
* [Taking a Tidelift subscription](https://tidelift.com/), or
* [GitHub Sponsor me](https://github.com/sponsors/vorburger),

**to support future maintenance!**

**Comment by vorburger** [comment]
Actually, I forgot that `main` is already the `3.1.0-SNAPSHOT` now! 

I don't want to release 3.0.2 and then support a 3.0.x... or at least not "for free". Please sponsor the project if you do need it.

#918 to release a 3.1.0 now is probably a good idea instead though.

**Comment by vorburger** [comment]
The existing `mariaDB4j-3.0.2` Git tag is causing [this problem](https://github.com/MariaDB4j/MariaDB4j/issues/918#issuecomment-2024092943) for the 3.1.0 release in #918.

I'm therefore deleting it from Git, hoping doing so fixes that problem.

For the record, it was b26ecd2611c34f9674b71ad8dbfc36cc87e43749.

**Comment by vorburger** [comment]
Closing this in favor of the (about to be completed) #918, as now no intention to do this anymore.

**Comment by fmartinou** [comment]
Thank you very much for the `3.1.0` release 👍
